## Library included:

In [1]:
import tensorflow as tf
import numpy as np

## Simple regression
There is only a loss function in here, the aim is to find a 'w' that amkes the loss function equal to 0. The answer should be -1.

In [2]:
w = tf.Variable(tf.constant(5, dtype=tf.float32))
lr = 0.2
epoch = 31

for epoch in range(epoch):  # 定義頂層循環
    with tf.GradientTape() as tape: # 這裡面裝著 loss function
        loss = tf.square(w + 1)
    grads = tape.gradient(loss, w)  # tape.gradient(loss, w) 告知 loss 對 w 求導，返回結果

    w.assign_sub(lr * grads)  # .assign_sub 对变量做自减 即：w -= lr*grads 即 w = w - lr*grads
    if epoch % 5 == 0:
        print("After %s epoch,w is %f,loss is %f" % (epoch, w.numpy(), loss))

# lr初始值：0.2   请自改学习率  0.001  0.999 看收敛过程
# 最终目的：找到 loss 最小 即 w = -1 的最优参数w

After 0 epoch,w is 2.600000,loss is 36.000000
After 5 epoch,w is -0.720064,loss is 0.217678
After 10 epoch,w is -0.978232,loss is 0.001316
After 15 epoch,w is -0.998307,loss is 0.000008
After 20 epoch,w is -0.999868,loss is 0.000000
After 25 epoch,w is -0.999990,loss is 0.000000
After 30 epoch,w is -0.999999,loss is 0.000000


## Tensor
Tensor is like an array. It can be of any dimension and contains value of many types. <br>

| Dimension | Name | Example |
|--|--|:--|
|0-D|Scalar|s = 123|
|1-D|Vector|v = [1, 2, 3]|
|2-D|Matrix|m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
|n-D|Tensor|t = [[[..|

The number of '[' indicate the dimension of tensor.

### Create a tensor
```tf.constant(<content>, dtype = <optional_datatype>)``` <br>
The vectors are placed horizontally. The first number in shape represent the dimension of the tensor, the second number represent the dirmension in each element.

### Data type
* tf.int, tf.float <br>
```tf.int32```, ```tf.float32```, ```tf.float 64```.

* tf.bool <br>
```tf.constant([True, False])```

* tf.string <br>
```tf.constant("Hello, world!")```

In [3]:
a = tf.constant([1, 4, 5], dtype = tf.int64)
print(a)
print(a.dtype)
print(a.shape)

tf.Tensor([1 4 5], shape=(3,), dtype=int64)
<dtype: 'int64'>
(3,)


In [4]:
a = tf.constant([[1, 4], [3, 5], [5, 8]], dtype = tf.int64)
print(a)
print(a.dtype)
print(a.shape)

tf.Tensor(
[[1 4]
 [3 5]
 [5 8]], shape=(3, 2), dtype=int64)
<dtype: 'int64'>
(3, 2)


### Create special tensor
Create Zeros tensor, ones tensor and tensor with certain value.

In [5]:
print(tf.zeros(5))
print(tf.ones([2,3]))
print(tf.fill([2,2], 3))

tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[3 3]
 [3 3]], shape=(2, 2), dtype=int32)


### Create tensor from numpy

In [6]:
a = np.arange(0, 5)
b = tf.convert_to_tensor(a, dtype=tf.int64)
print(a)
print(b)

[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)


### Create tensor from normal distribution
First parameter is the dimension of the tensor. Default mean is 0 and SD is 1.

In [7]:
print(tf.random.normal([2, 5], mean = 50, stddev = 15))

tf.Tensor(
[[54.145004 54.562878 19.547676 46.921375 60.87916 ]
 [46.70141  46.667973 35.0382   58.802418 54.163006]], shape=(2, 5), dtype=float32)


More centered values. If the values are all inside (mean - 2 * SD, mean + 2 * SD).

In [8]:
print(tf.random.truncated_normal([2, 5], 50, 15))

tf.Tensor(
[[42.49601  66.07817  49.463253 51.933193 56.431747]
 [52.092037 38.015923 70.97705  56.08771  39.77851 ]], shape=(2, 5), dtype=float32)


### Create tensor from uniform distribution

In [9]:
print(tf.random.uniform([2, 5], minval = 1, maxval = 100))

tf.Tensor(
[[82.88438   14.931198   4.87821   40.19487   29.956982 ]
 [ 7.9153237 41.451706  20.707136  11.394931  71.61198  ]], shape=(2, 5), dtype=float32)


## Tensor operations
### Type transform

In [10]:
a = tf.constant([1, 2], tf.int32)
b = tf.cast(a, tf.float32)
print(b)

tf.Tensor([1. 2.], shape=(2,), dtype=float32)


### Find maximum and minimum
The return is also of tensor type.

In [11]:
a = tf.constant([[1, 2], [3, 4]], tf.int32)
print(tf.reduce_max(a))
print(tf.reduce_min(a))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


### + - * / Calculation
For tensors with same dimensions.

In [12]:
a = tf.fill([2, 2], 3.)    # Use '3.' to set the type to float
b = tf.ones([2, 2])
print(tf.add(a, b))
print(tf.subtract(a, b))
print(tf.multiply(a, b))
print(tf.divide(a, b))

tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3. 3.]
 [3. 3.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3. 3.]
 [3. 3.]], shape=(2, 2), dtype=float32)


### Power calculation
Include square, power and square root calculations.

In [13]:
print(tf.square(a))
print(tf.pow(a, 3))
print(tf.sqrt(a))

tf.Tensor(
[[9. 9.]
 [9. 9.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[27. 27.]
 [27. 27.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.7320508 1.7320508]
 [1.7320508 1.7320508]], shape=(2, 2), dtype=float32)


### Matrix multiplication

In [14]:
print(tf.matmul(a, b))

tf.Tensor(
[[6. 6.]
 [6. 6.]], shape=(2, 2), dtype=float32)


### Axix
In a 2D tensor, we can conduct operation along a axis and return the results in a vector form, through axis setting. axis = 0 means every column is a group, axis = 1 means every row is a group. If the axis is not given, the operation include all elements in the tensor.

In [15]:
a = tf.constant([[1, 2], [3, 4], [5, 6]])
print(a)
print(tf.reduce_mean(a))    # Mean for all elements
print(tf.reduce_mean(a, 0))    # Mean for each column
print(tf.reduce_sum(a, 1))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([ 3  7 11], shape=(3,), dtype=int32)


### Find index of maximum and minimum

In [16]:
test = np.array([[1, 2, 3], [2, 3, 4], [5, 4, 3], [8, 7, 2]])
print("test:\n", test)
print("Index of the largest in each column: ", tf.argmax(test, axis=0))
print("Index of the largest in each row: ", tf.argmax(test, axis=1))

test:
 [[1 2 3]
 [2 3 4]
 [5 4 3]
 [8 7 2]]
Index of the largest in each column:  tf.Tensor([3 3 1], shape=(3,), dtype=int64)
Index of the largest in each row:  tf.Tensor([2 2 0 0], shape=(4,), dtype=int64)


### Create dataset
```tf.data.Dataset.from_tensor_slices((<features>, <labels>))``` <br>
Input the input vector and output vector as key-value pair to make a dataset. This function works for both tensor and numpy.

In [17]:
features = tf.constant([12, 23, 10, 17])
labels = tf.constant([0, 1, 1, 0])
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
for element in dataset:
    print(element)

(<tf.Tensor: shape=(), dtype=int32, numpy=12>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=23>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=17>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


### Transfer dataset to One-hot form

In [18]:
classes = 3
labels = tf.constant([1, 0, 2])  # labels 有三個不同的 label
output = tf.one_hot(labels, depth = classes)
print("result of labels1:", output)

result of labels1: tf.Tensor(
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


## Variable
We can use ```tf.Variable()``` to make a variable to be trainable. The variable will then record its gradient through backpropagation. This will be done to all the parameters that we need to train.

In [19]:
w = tf.Variable(tf.random.normal([2, 2], 0, 1))

### Gradient calculation
Use ```with``` structure to record the computation of tensor, and use ```gradient()``` to calculate the gradient of this tensor.

In [20]:
with tf.GradientTape() as tape:
    x = tf.Variable(tf.constant(3.0))
    loss = tf.pow(x, 2)
grad = tape.gradient(loss, x)
print(grad)    # 2 * 3.0

tf.Tensor(6.0, shape=(), dtype=float32)


### Softmax calculation

In [21]:
y = tf.constant([1.01, 2.01, -0.66])
y_pro = tf.nn.softmax(y)
print("After softmax, y_pro is:", y_pro)  # y_pro 符合概率分佈

After softmax, y_pro is: tf.Tensor([0.25598174 0.69583046 0.0481878 ], shape=(3,), dtype=float32)


### Update parameters
The parameters must be trainable. <br>
```w.assign_sub(x)``` is equal to ```w -= x```.

In [22]:
w = tf.Variable(4)
w.assign_sub(1)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>
